spring:
  config:
    activate:
      on-profile: prod


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kkosoonnae-db.c3qacaik290s.ap-northeast-2.rds.amazonaws.com:3306/kkosoonnae?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: k2winner*

