spring:
  profiles:
    active: local #default
    group:
      local:
        - jwt
      prod:
        - jwt
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
security:
  jwt:
    secret-key: KkoSoonNaeFinalProJectKkoSoonNaeFinalProJect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kkosoonnae?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12341234