server:
  port: 8080

spring:
  profiles:
    active: local #default
    group:
      local:
        - jwt
        - aws
      prod:
        - jwt
        - aws
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

cloud:
  aws:
    s3:
      bucket: kkosoonnae-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true
logging:
  config: classpath:logback-spring.xml